---
title: "Investigating spatial distributions of late-successional forest in western Oregon"
author: Mary Kelly and Randy Swaty
date: October 15, 2023
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Late-successional forests are typically defined by age, lack of disturbance, or tree height. In addition to hosting relatively high biodiversity, these forests can be important carbon sinks and are a focus of the 2021 Infrastructure Investment and Jobs Act under the Biden-Harris Administration.

Disturbance-dependent ecosystems may have ‘open-canopy’ late succession habitat. For example, riparian area ecosystems may naturally have frequent ice scouring and/or flooding that removes some, but not all trees. Fire adapted ecosystems may have frequent surface fires that keep the canopy relatively open while preserving older and taller trees.  If we only consider ‘closed-canopy’ late succession habitat, we may underestimate those areas, and more importantly we may 1) miss areas for conservation and 2) miss trends of loss or gain. Further, due to changes in disturbance regimes, for example dam creation and fire-suppression, these potential open-canopy late succession habitats may need restoration.


[Figure 1. Creative commons photo of late successional forest]

Our guiding questions for this project are:

1) What are the ecosystems for the area of interest?
2) How much late succession would there have been historically vs. today?
3) What happens when we split late-succession into open and closed canopy types?


